"""add_studio_and_single_room_fields

Revision ID: 785d31cd7499
Revises: 
Create Date: 2025-05-18 02:43:23.821982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785d31cd7499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studio_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('studio_available', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('single_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('single_available', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.String(length=255), nullable=False))

    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_column('contact_info')
        batch_op.drop_column('single_available')
        batch_op.drop_column('single_count')
        batch_op.drop_column('studio_available')
        batch_op.drop_column('studio_count')

    # ### end Alembic commands ###
