"""add user's school_email

Revision ID: 894fee380913
Revises: f3a4392508a3
Create Date: 2025-05-09 02:53:37.637524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894fee380913'
down_revision = 'f3a4392508a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_email', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_school_email', ['school_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_school_email', type_='unique')
        batch_op.drop_column('school_email')

    # ### end Alembic commands ###
