"""Initial migration

Revision ID: cd3ec5fa45e9
Revises: 
Create Date: 2025-05-07 18:02:09.113841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3ec5fa45e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('appliance', 'furniture', 'security', 'utility', 'other', name='amenity_category_enum'), nullable=True),
    sa.PrimaryKeyConstraint('amenity_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.Enum('student', 'landlord', 'admin', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('portal_id')
    )
    op.create_table('accommodations',
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Enum('apartment', 'studio', 'house', 'shared_room', 'single_room', name='property_type_enum'), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('bathroom_count', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('rent_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_furnished', sa.Boolean(), nullable=True),
    sa.Column('has_water_bill', sa.Boolean(), nullable=True),
    sa.Column('has_electricity_bill', sa.Boolean(), nullable=True),
    sa.Column('has_internet', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('distance_to_university', sa.Float(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('minimum_stay', sa.Integer(), nullable=True),
    sa.Column('maximum_stay', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('available', 'pending', 'rented', 'unavailable', name='accommodation_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('accommodation_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.Enum('system', 'lease', 'maintenance', 'message', 'review', 'other', name='notification_type_enum'), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('student_verifications',
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('verification_document', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verification_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_table('accommodation_amenities',
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], ),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.amenity_id'], ),
    sa.PrimaryKeyConstraint('accommodation_id', 'amenity_id')
    )
    op.create_table('accommodation_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'accommodation_id')
    )
    op.create_table('leases',
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lease_document', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'terminated', 'renewal_pending', name='lease_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lease_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('safety_rating', sa.Integer(), nullable=True),
    sa.Column('cleanliness_rating', sa.Integer(), nullable=True),
    sa.Column('landlord_rating', sa.Integer(), nullable=True),
    sa.Column('value_rating', sa.Integer(), nullable=True),
    sa.Column('location_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('sublets',
    sa.Column('sublet_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('available_to', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'fulfilled', 'expired', 'canceled', name='sublet_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], ),
    sa.ForeignKeyConstraint(['poster_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sublet_id')
    )
    op.create_table('fraud_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('sublet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('scam', 'fake_listing', 'misleading_info', 'illegal_activity', 'other', name='fraud_reason_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'investigating', 'resolved', 'rejected', name='fraud_status_enum'), nullable=True),
    sa.Column('admin_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sublet_id'], ['sublets.sublet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('maintenance_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'emergency', name='urgency_enum'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'in_progress', 'resolved', 'rejected', name='maintenance_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('landlord_response', sa.Text(), nullable=True),
    sa.Column('resolution_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.lease_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('maintenance_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.request_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_images')
    op.drop_table('maintenance_requests')
    op.drop_table('fraud_reports')
    op.drop_table('sublets')
    op.drop_table('reviews')
    op.drop_table('leases')
    op.drop_table('favorites')
    op.drop_table('accommodation_images')
    op.drop_table('accommodation_amenities')
    op.drop_table('student_verifications')
    op.drop_table('notifications')
    op.drop_table('accommodations')
    op.drop_table('users')
    op.drop_table('amenities')
    # ### end Alembic commands ###
