"""add sepatate areas for room types

Revision ID: e191f1c1fe8c
Revises: 742bf78bd825
Create Date: 2025-05-18 03:35:49.439389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e191f1c1fe8c'
down_revision = '742bf78bd825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studio_area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('single_area', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_column('single_area')
        batch_op.drop_column('studio_area')

    # ### end Alembic commands ###
