"""update user enum

Revision ID: e3010c43d3c2
Revises: cd3ec5fa45e9
Create Date: 2025-05-08 02:04:14.612006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3010c43d3c2'
down_revision = 'cd3ec5fa45e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('student', 'landlord', 'admin', 'moderator', name='user_role_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_role',
               existing_type=sa.Enum('student', 'landlord', 'admin', 'moderator', name='user_role_enum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
